# Generated by Django 4.1.3 on 2022-11-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_org', models.CharField(max_length=255)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=20)),
                ('service', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
    ]
