# Generated by Django 4.1.3 on 2022-11-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
